FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    libjpeg-dev \
    zlib1g-dev \
    gettext \
    wget \
    procps \
    git \
    && rm -rf /var/lib/apt/lists/* 

RUN mkdir /code
WORKDIR /code
ADD backend/requirements.txt /code/
RUN pip install --no-cache-dir -r requirements.txt