FROM python:3.11-alpine
ENV PYTHONUNBUFFERED 1
RUN apk add --no-cache build-base python3-dev py-pip jpeg-dev zlib-dev
ENV LIBRARY_PATH=/lib:/usr/lib
RUN mkdir /code
WORKDIR /code
ADD backend/requirements.txt /code/
RUN pip install -r requirements.txt
ADD ./backend /code/