# Generated by Django 4.2.10 on 2024-10-24 12:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_h1', models.CharField(blank=True, max_length=255, verbose_name='H1')),
                ('meta_h1_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1')),
                ('meta_h1_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('meta_title_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('meta_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('meta_description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
                ('meta_description_uk', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('meta_description_ru', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('meta_keywords', models.TextField(blank=True, max_length=255, verbose_name='Keywords')),
                ('meta_keywords_uk', models.TextField(blank=True, max_length=255, null=True, verbose_name='Keywords')),
                ('meta_keywords_ru', models.TextField(blank=True, max_length=255, null=True, verbose_name='Keywords')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Содержание')),
                ('content_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Страница "О нас"',
                'verbose_name_plural': 'Страница "О нас"',
            },
        ),
    ]
