# Generated by Django 4.2.10 on 2024-05-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='E-Mail для контактов')),
                ('form_email', models.EmailField(max_length=255, verbose_name='E-Mail для форм')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('operator', models.SmallIntegerField(blank=True, choices=[(1, 'Киевстар')], default=1, null=True, verbose_name='Оператор')),
                ('fb_link', models.URLField(blank=True, null=True, verbose_name='Ссылка Facebook')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Ссылка Instagram')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
    ]
