# Generated by Django 4.2.10 on 2024-10-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='meta_description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='meta_description_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='meta_description_uk',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='meta_h1',
            field=models.CharField(blank=True, max_length=255, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='meta_h1_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='meta_h1_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='meta_keywords',
            field=models.TextField(blank=True, max_length=255, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='meta_keywords_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='meta_keywords_uk',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='meta_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
