# Generated by Django 4.2.10 on 2024-10-23 12:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactdata_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='address',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='address_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='address_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Адрес'),
        ),
    ]
