# Generated by Django 4.2.10 on 2024-10-22 14:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_h1', models.CharField(blank=True, max_length=255, verbose_name='H1')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('meta_description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
                ('meta_keywords', models.TextField(blank=True, max_length=255, verbose_name='Keywords')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Страница "Доставка"',
                'verbose_name_plural': 'Страница "Доставка"',
            },
        ),
    ]
