# Generated by Django 4.2.10 on 2024-10-22 14:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_deliverypage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypage',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='deliverypage',
            name='content_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='deliverypage',
            name='meta_description_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='deliverypage',
            name='meta_description_uk',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='deliverypage',
            name='meta_h1_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='deliverypage',
            name='meta_h1_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='deliverypage',
            name='meta_keywords_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='deliverypage',
            name='meta_keywords_uk',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='deliverypage',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='deliverypage',
            name='meta_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
