# Generated by Django 2.0.5 on 2018-05-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180510_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='E-Mail для контактов')),
                ('form_email', models.EmailField(max_length=255, verbose_name='E-Mail для форм')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('fb_link', models.URLField(blank=True, null=True, verbose_name='Ссылка Facebook')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Ссылка Instagram')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='Ссылка Twitter')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
    ]
