# Generated by Django 2.0.5 on 2018-05-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedata',
            name='ga_html',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='HTML-код Google Analytics'),
        ),
    ]
