# Generated by Django 2.0.5 on 2018-06-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_pagedata_ga_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='operator',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Киевстар')], default=1, null=True, verbose_name='Оператор'),
        ),
    ]
