# Generated by Django 2.0.5 on 2018-06-21 11:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contactdata_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Длинное описание'),
        ),
    ]
