# Generated by Django 4.2.10 on 2024-03-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedata',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description (мета-тег)'),
        ),
        migrations.AddField(
            model_name='pagedata',
            name='meta_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Description (мета-тег)'),
        ),
        migrations.AddField(
            model_name='pagedata',
            name='meta_h1_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег h1 (мета-тег)'),
        ),
        migrations.AddField(
            model_name='pagedata',
            name='meta_h1_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег h1 (мета-тег)'),
        ),
        migrations.AddField(
            model_name='pagedata',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords (мета-тег)'),
        ),
        migrations.AddField(
            model_name='pagedata',
            name='meta_keywords_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords (мета-тег)'),
        ),
        migrations.AddField(
            model_name='pagedata',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (мета-тег)'),
        ),
        migrations.AddField(
            model_name='pagedata',
            name='meta_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (мета-тег)'),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pagedata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
