# Generated by Django 4.2.10 on 2024-03-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_pagedata_meta_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
