# Generated by Django 4.2.10 on 2024-05-10 09:13

import apps.products.utils
import ckeditor_uploader.fields
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('slug', models.SlugField(default='', max_length=255, verbose_name='Slug (для url)')),
                ('weight', models.IntegerField(default=1000, help_text='Чем больше вес, тем выше на странице находится этот тип продукта.', verbose_name='Вес')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включено')),
            ],
            options={
                'verbose_name': 'Тип продукта',
                'verbose_name_plural': 'Типы продуктов',
                'ordering': ('-weight',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('slug', models.SlugField(null=True, verbose_name='Slug')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('short_description_uk', models.CharField(max_length=255, null=True, verbose_name='Краткое описание')),
                ('short_description_ru', models.CharField(max_length=255, null=True, verbose_name='Краткое описание')),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Длинное описание')),
                ('long_description_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Длинное описание')),
                ('long_description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Длинное описание')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=apps.products.utils.get_products_upload_to_folder, verbose_name='Изображение')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('types', models.ManyToManyField(to='products.producttype', verbose_name='Тип продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукция',
                'ordering': ('title',),
            },
        ),
    ]
