# Generated by Django 4.2.10 on 2024-09-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Краткое описание (главная страница)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание (главная страница)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание (главная страница)'),
        ),
    ]
