# Generated by Django 4.2.10 on 2024-10-03 19:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_related_products_product_short_description_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description_2_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Краткое описание (страница товара)'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_2_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Краткое описание (страница товара)'),
        ),
    ]
