# Generated by Django 4.2.10 on 2024-10-03 20:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPaymentDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('block_title', models.CharField(max_length=255, verbose_name='Название блока')),
                ('block_title_uk', models.CharField(max_length=255, null=True, verbose_name='Название блока')),
                ('block_title_ru', models.CharField(max_length=255, null=True, verbose_name='Название блока')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание')),
                ('content_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Содержание')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Описание оплаты и доставки',
                'verbose_name_plural': 'Описание оплаты и доставки',
            },
        ),
        migrations.AddField(
            model_name='productproperty',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='value_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='value_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Значение'),
        ),
    ]
