# Generated by Django 4.2.10 on 2024-10-06 10:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_deliverypaymentdescription_productproperty_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverypaymentdescription',
            options={'verbose_name': 'Оплата и доставка', 'verbose_name_plural': 'Оплата и доставка'},
        ),
        migrations.AddField(
            model_name='product',
            name='price_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Не будет отображаться на странице товара если включено поле "Стоимость неизвестна".', null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Не будет отображаться на странице товара если включено поле "Стоимость неизвестна".', null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Не будет отображаться на странице товара если включено поле "Стоимость неизвестна".', null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_unknown',
            field=models.BooleanField(default=False, verbose_name='Стоимость неизвестна'),
        ),
    ]
